### ISSUE TITLE
Using non-composited-animations leads to layout and style recalculations

### ISSUE THREAD

**Issue by botanegg** [pajasevi/CSSnowflakes#2]
Due to using `top` property in css animation browsers leads to recalculate styles and layout  
To avoid this recalculation we should use only `transform` or `opacity` properties  

For current animation we can change `snowflakes-fall` keyframes to
```css
transform: translateY(0vh);
...
transform: translateY(110vh);
```
But it leads to duplicate `transform` properties in `.snowflake` elements (due to animation cascade)

To apply second `transform` property we can wrap our `.snowflake` elements to other `div` (for example witn `.inner` class) and split animation by two independent part

Details:
- https://web.dev/non-composited-animations/
- https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count

<details>
  <summary>Final Example for single snowflake</summary>
  
  ```html
  <div class=".snowflake">
    <div class=".inner">❅</div>
  </div>
  ```

  ```css
@keyframes snowflakes-fall {
    0% {
      transform: translateY(0vh);
      /* opacity: 1; also composited */
    }
  
    100% {
      transform: translateY(110vh); /* using 110vh due to initial top:-10% in .snowflake */
      /* opacity: 0; also composited */
    }
  }
  
  @keyframes snowflakes-shake {
    0% {
      transform: translateX(0px);
    }
  
    50% {
      transform: translateX(80px);
    }
  
    100% {
      transform: translateX(0px);
    }
  }
  
  .snowflake {
    position: fixed;
    top: -10%;
    z-index: 9999;
    user-select: none;
    cursor: default;
  
    animation-name: snowflakes-shake;
    animation-duration: 3s;
    animation-timing-function: ease-in-out;
    animation-iteration-count: infinite;
    animation-play-state: running;
  }
  
  .snowflake .inner {
    animation-name: snowflakes-fall;
    animation-duration: 10s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-play-state: running;
  }
  
  .snowflake:nth-of-type(1) {
    left: 1%;
    animation-delay: 0s;
  }
  
  .snowflake:nth-of-type(1) .inner {
    animation-delay: 0s;
  }
  ```
  
</details>

This approach reduces Layouts and Style recals from ~100 to 0 and CPU usage from 3.5% to 0.1% for Demo Page on my PC;
